### PR TITLE
♻ Refactor Frontend (Design and Logic)

### LINKED ISSUE #22: Move frontend into CRA application
This is needed for optimal compatibility when developing on most devices.

### PR DESCRIPTION
**Pull request by anarmawala**
-  ✨ Using redux hooks to store central User state
- 🎨 Separating pages (SOC)
- 💄 Using react-bootstrap instead of Material-UI
- 🚸 Improving user workflow through automated redirection

### CODE REVIEW

**Comment by alexchomiak** [comment]
I migrated the client to a CRA app for less multiplatform headaches because the guys at Facebook do better than me with their webpack configs 🤷‍♂ Checkout my changes and LMK what you think!

**Comment by bmiddha** [comment]
branch rebased

**Review by jigar288 — APPROVED** [review]
LGTM

**Comment by anarmawala** [comment]
@bmiddha Move to CRA in cd8232f24258c11374fc82d8e6921f1f69b273de broke GA and Docker config. 

We will need to make sure that docker compose still gets everything up in regards to the client.

**Comment by anarmawala** [comment]
@clarkchentw Can you take a look at the API tests and fix based on new changes?

**Review by alexchomiak — APPROVED** [review]
LGTM 👍 The changes finally pass the test cases and the frontend is built in a much more scalable fashion now!

**Review by bmiddha — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
