### PR TITLE
:sparkles: Added Input Validation

### PR DESCRIPTION
**Pull request by anarmawala**
✨ Added required password strength
✨ Added checking for valid email according to W3C standard
✨ Added field validation on front and back end

### CODE REVIEW

**Review by alexchomiak — COMMENTED** [review]
This looks good. Having the same code for regex tests in the signup and login components is a bit redundant. That can be fixed in future code cleaning updates by exporting input validation into a utils file. For now this looks great!

**Comment by alexchomiak** [comment]
Actually I just found a bug, the signup is messed up, I put an invalid password and it gives me an email already exists error, and it exits the signup component which is undesirable behavior.

**Comment by clarkchentw** [comment]
> Actually I just found a bug, the signup is messed up, I put an invalid password and it gives me an email already exists error, and it exits the signup component which is undesirable behavior.

That was fixed in my other pull request

**Comment by alexchomiak** [comment]
Is it merged into this branch yet? @clarkchentw

**Comment by alexchomiak** [comment]
Pulling changes now, I also realized I didn't restart my dev docker-compose after switching branches, which led to weird issues. Restarted and everything is working fine! 👍

**Comment by clarkchentw** [comment]
> Is it merged into this branch yet? @clarkchentw

Just did

**Comment by alexchomiak** [comment]
@clarkchentw Testing everything right now and the new validation is working as expected. I would like to work on some client-side things right now and would like to avoid the possibility of merge-conflicts. I think everything is fine to merge, does that sound fine to you?

**Review by alexchomiak — APPROVED** [review]

**Pull request merged**
