### PR TITLE
:sparkles: added email notifications with twilio

### PR DESCRIPTION
**Pull request by alexchomiak**
✨ Added email notifications with Twilio's SendGrid API
✨ Created pipeline to add different notification types
🚧 Prepared API for the consumption of Banner API Services

### CODE REVIEW

**Comment by alexchomiak** [comment]
Messed up commit messages ^^
The last two commits:
✅ Got tests passing
🎨 Fixed formatting

**Review by bmiddha — CHANGES_REQUESTED** [review]
Looks good.
Can you add prettier to eslint instead of running it separately, that way the ci pipelines and pre-commit hooks will handle formatting with linting? That should also prevent eslint and prettier rule conflicts
https://prettier.io/docs/en/integrating-with-linters.html

**Review by bmiddha — APPROVED** [review]
I have added prettier config to eslint stuffs

**Comment by alexchomiak** [comment]
👍 Thanks, just checked it out and everything looks good. You have earned your honorary taco! 🌮 
taco-day-eryday

**Pull request merged**
