### PR TITLE
Create progress-report-checkpoint-4

### PR DESCRIPTION
**Pull request by jigar288**

### CODE REVIEW

**Review by clarkchentw — APPROVED** [review]
Looks good to me, we’re working on doc together

**Review by alexchomiak — APPROVED** [review]
👍 Thanks Jigar for writing this awesome progress report! Here's a taco! 🌮

**Review by anarmawala — COMMENTED** [review]
Would it be possible to move this into a logistics folder?

**Comment by alexchomiak** [comment]
@anarmawala We'll just do that after checkpoint 4 is due

**Pull request merged**
