### PR TITLE
🚨🐛✨ App Polish

### LINKED ISSUE #90: PWA is not installable.
Service worker does not return 200 when the app is offline, resulting in PWA not being installable.

Lighthouse PWA Audit:
image

### PR DESCRIPTION
**Pull request by anarmawala**
**WIP**: Ongoing Refactor

- 🚨 Removed all explicit any on client side
- ✨ Use `redux-thunk` for everything
      -  Sign Up
      -  Sign In
      -  Sign Out
      -  Update User

- 💥 Rework file structure for `redux`
- 🐛 Fix Aliasing (`typescript` and `webpack` config)

### CODE REVIEW

**Review by bmiddha — APPROVED** [review]
Looks good! 💃🎉🎊🥳

**Review by jigar288 — APPROVED** [review]
Great work! This looks good to me

**Review by alexchomiak — APPROVED** [review]
👍 Great changes to the code base, the Redux typing fix is nice. Could you make a PR with these changes to my Goto react app repo??

**Comment by alexchomiak** [comment]
@bmiddha 
taco-gif

**Comment by bmiddha** [comment]
This PR is getting pretty big. We should merge this soon.
@anarmawala

**Pull request merged**
