### PR TITLE
👷‍♂️🗑cleanup files, patch actions

### PR DESCRIPTION
**Pull request by bmiddha**
- removed redundant config files
- moved .github folder out of api to make github actions work. github actions only run if the .github dir is in the root of the repo.
- added github action to build client

### CODE REVIEW

**Comment by bmiddha** [comment]
I'll fix build breaks in another PR. Seems to be an issue with building sass. Similar to the issue in https://github.com/acm-uic/sigwebdev-authenticated-todo that @alexchomiak and I faced.

**Review by alexchomiak — COMMENTED** [review]
Why are you deleting the prettier rcs?

**Comment by bmiddha** [comment]
> Why are you deleting the prettier rcs?

We don't need one per folder. 
There is still one in the root of the repo. 
That should apply to everything.
Same applies for the gitignore files

**Review by alexchomiak — APPROVED** [review]
Oof that's my bad, didn't see the one in the root of the repo. Everything else looks good. 👍

**Pull request merged**
